#!/bin/bash

set -e

export CC="${DEB_HOST_GNU_TYPE}"-gcc
export CXX="${DEB_HOST_GNU_TYPE}"-g++
export PKG_CONFIG="${DEB_HOST_GNU_TYPE}"-pkg-config

export CONFIG_OPTIONS="--host=${DEB_HOST_GNU_TYPE}"

export CGO_ENABLED=1
export GOPATH="`pwd`/go-workspace"

eval `debian/goflags.guess ${DEB_HOST_ARCH}`

#paths
PACKAGE=github.com/armPelionEdge/maestro-shell
MAESTRODIR="$GOPATH"/src/"$PACKAGE"
GREASEGODIR="$MAESTRODIR"/vendor/github.com/armPelionEdge/greasego
GREASELIBDIR="$GREASEGODIR"/deps/src/greaseLib

#Import GO project maestro-shell
GO111MODULE=auto go get github.com/armPelionEdge/maestro-shell || true
cd "$GOPATH"/src/github.com/armPelionEdge/maestro-shell
git checkout "$PACKAGE_BRANCH"

#build the deps
./build-deps.sh

#build the app
GO111MODULE=auto go build -buildmode=pie --tags debug "$PACKAGE"
