ARG PREFIX
FROM ${PREFIX}pelion-jammy-build

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
		apt-rdepends \
		git  \
		lintian \
		python3 \
		quilt \
		ssh \
		vim

USER user
