#!/bin/bash

set -e

export GOPATH="$(pwd)/go-workspace"

eval "$(debian/goflags.guess $DEB_HOST_ARCH)"

package=k8s.io/kubernetes
packagedir=$GOPATH/src/$package
origpath="$(pwd)"

rm -rf "$GOPATH"
set -- *
mkdir -p "$packagedir"
cp -r "$@" "$packagedir"/

cd "$packagedir"
KUBE_VERBOSE=0 GO111MODULE=auto make kubelet KUBE_BUILD_PLATFORMS="${DEB_HOST_ARCH_OS}/${GOARCH}"
