#!/bin/sh

set -e

export CC="${DEB_HOST_GNU_TYPE}"-gcc
export CXX="${DEB_HOST_GNU_TYPE}"-g++
export PKG_CONFIG="${DEB_HOST_GNU_TYPE}"-pkg-config

export CONFIG_OPTIONS="--host=${DEB_HOST_GNU_TYPE}"

export CGO_ENABLED=1
export GOPATH="`pwd`/go-workspace"
# fix go's weird habit of checking out code read-only
export GOFLAGS="${GOFLAGS} -modcacherw"

eval `debian/goflags.guess ${DEB_HOST_ARCH}`

PACKAGE=github.com/PelionIoT/maestro
MAESTRODIR="$GOPATH"/src/"$PACKAGE"

rm -rf "$GOPATH"
set -- *
mkdir -p "$MAESTRODIR"
cp -r "$@" "$MAESTRODIR"/

cd "$MAESTRODIR"/maestro
GO111MODULE=auto go build -buildmode=pie "$PACKAGE"/maestro
