unixLogSocket: /tmp/grease.socket
sysLogSocket: /run/systemd/journal/syslog
linuxKernelLog: false
httpUnixSocket: /tmp/maestroapi.sock
configDBPath: /var/lib/pelion/maestro/maestroConfig.db
imagePath: /tmp/maestro/images
scratchPath: /tmp/maestro/scratch
clientId: "{{ARCH_SERIAL_NUMBER}}"
network:
  disable: true
var_defs:
  - key: "TMP_DIR"
    value: "/tmp"
  - key: "WIGWAG_NODE_PATH"
    value: "/usr/lib/pelion/devicejs-core-modules/node_modules"
  - key: "WIGWAG_DIR"
    value: "/usr/lib/pelion"
  - key: "NODE_EXEC"
    value: "/usr/lib/pelion/bin/node"
  - key: "MAESTRO_RUNNER_DIR"
    value: "/usr/lib/pelion/devicejs-core-modules/maestroRunner"
  - key: "LOCAL_DEVICEDB_PORT"
    value: 9000
  - key: "LOCAL_DATABASE_STORAGE_DIRECTORY"
    value: "/var/lib/pelion/devicedb"
  - key: "RELAY_VERSIONS_FILE"
    value: "/etc/pelion/versions.json"
  - key: "FACTORY_VERSIONS_FILE"
    value: "/etc/pelion/factory/versions.json"
  - key: "USER_VERSIONS_FILE"
    value: "/etc/pelion/user/versions.json"
  - key: "UPGRADE_VERSIONS_FILE"
    value: "/etc/pelion/upgrade/versions.json"
targets:
  - file: "/var/log/pelion/maestro.log"
    rotate:
      max_files: 4
      max_file_size: 10000000 # 10MB max file size
      max_total_size: 42000000
      rotate_on_start: true
    delim: "\n"
    format_time: "[%ld:%d] "
    format_level: "<%s> "
    format_tag: "{%s} "
    format_origin: "(%s) "
    filters:
      - levels: warn
        format_pre: "\u001B[33m" # yellow
        format_post: "\u001B[39m"
      - levels: error
        format_pre: "\u001B[31m" # red
        format_post: "\u001B[39m"
static_file_generators:
  - name: "devicedb"
    template_file: "/etc/pelion/template/template.devicedb.conf"
    output_file: "/etc/pelion/devicedb.yaml"
  - name: "relayTerm"
    template_file: "/etc/pelion/template/relayTerm.template.json"
    output_file: "/etc/pelion/relay-term-config.json"
config_end: true
