unixLogSocket: /tmp/grease.socket
sysLogSocket: /run/systemd/journal/syslog
linuxKernelLog: false
httpUnixSocket: /tmp/maestroapi.sock
configDBPath: /var/lib/pelion/maestro/maestroConfig.db
clientId: "{{ARCH_SERIAL_NUMBER}}"
processes:
    reaper_interval: 1500
network:
  disable: true
platform_readers:
  - platform: "fsonly"
    params:
      identityPath: "/var/lib/pelion/edge_gw_config/identity.json"
gateway_capabilities:
  edge_core_socketpath: "/tmp/edge.sock"
  lwm2m_objectid: 33457
  gateway_resources:
  - name: "urn:fid:pelion.com:fluentbit:1.0.0"
    enable: true
    config_filepath: "/etc/pelion/example.fluentbit.conf"
  - name: "urn:fid:pelion.com:terminal:1.0.0"
    enable: true
    config_filepath: "/etc/pelion/relay-term-config.json"
var_defs:
  - key: "TMP_DIR"
    value: "/tmp"
  - key: "MAESTRO_RUNNER_DIR"
    value: "/usr/lib/pelion/devicejs-core-modules/maestroRunner"
mdns:
  # disable: true
  static_records:
    - name: "WigWagRelay"
      service: "_wwservices._tcp" # normally something like https or ftp
      # domain: "local"     # local is default
      interfaces: "eth0"
      not_interfaces: "Witap0"
      port: 3131
      text:
        - "wwid={{ARCH_SERIAL_NUMBER}}"
      hostname: "wigwaggateway"
    - name: "WigWagRelay_{{ARCH_SERIAL_NUMBER}}"
      service: "_wwservices._tcp" # normally something like https or ftp
      # domain: "local"     # local is default
      interfaces: "eth0"
      not_interfaces: "Witap0"
      port: 3131
      text:
        - "wwid={{ARCH_SERIAL_NUMBER}}"
      hostname: "{{ARCH_SERIAL_NUMBER}}"
symphony:
  # symphony system management APIs
  # defaults to 10:
  disable_sys_stats: true
  sys_stats_count_threshold: 15 # send if you have 15 or more stats queued
  sys_stats_time_threshold: 120000 # every 120 seconds send stuff, no matter what
  #client_cert: "{{ARCH_CLIENT_CERT_PEM}}"
  #client_key: "{{ARCH_CLIENT_KEY_PEM}}"
  no_tls: true
  host: "gateways.local"
  url_logs: "http://gateways.local:8080/relay-logs/logs"
  url_stats: "http://gateways.local:8080/relay-stats/stats_obj"
  send_time_threshold: 120000 # set the send time threshold to 2 minutes
  # port: "{{ARCH_RELAY_SERVICES_PORT}}"
targets:
  - file: "/var/log/pelion/maestro.log"
    rotate:
      max_files: 4
      max_file_size: 10000000 # 10MB max file size
      max_total_size: 42000000
      rotate_on_start: true
    delim: "\n"
    format_time: "[%ld:%d] "
    format_level: "<%s> "
    format_tag: "{%s} "
    format_origin: "(%s) "
    filters:
      - level: log,user1,user2
        format_pre: "\u001B[39m"    # normal
      - level: trace
        format_pre: "\u001B[35m"    # purple
        format_post: "\u001B[39m"
      - level: info
        format_pre: "\u001B[2m"     # 'dim' text
        format_post: "\u001B[39m"
      - levels: success
        format_pre: "\u001B[32m"    # green
        format_post: "\u001B[39m"
      - levels: warn
        format_pre: "\u001B[33m"    # yellow
        format_post: "\u001B[39m"
      - levels: error
        format_pre: "\u001B[31m"    # red
        format_post: "\u001B[39m"
      - levels: debug
        format_pre: "\u001B[36m"    # cyan
        format_post: "\u001B[39m"
      - levels: debug2,debug3
        format_pre: "\u001B[34m"    # blue
        format_post: "\u001B[39m"
      - levels: log
        tag: stdout
        format_pre: "\u001B[39m"    # normal
        format_post: "\u001B[39m"
static_file_generators:
  - name: "relayTerm"
    template_file: "/etc/pelion/template/relayTerm.template.json"
    output_file: "/etc/pelion/relay-term-config.json"
config_end: true
