FROM pelion-focal-build

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
		apt-rdepends \
		git  \
		lintian \
		nodejs \
		python2.7 \
		quilt \
		ssh \
		vim

USER user
