unixLogSocket: /tmp/grease.socket
sysLogSocket: /run/systemd/journal/syslog
linuxKernelLog: false
httpUnixSocket: /tmp/maestroapi.sock
configDBPath: /var/lib/pelion/maestro/maestroConfig.db
imagePath: /tmp/maestro/images
scratchPath: /tmp/maestro/scratch
clientId: "{{ARCH_SERIAL_NUMBER}}"
network:
  disable: true
var_defs:
  - key: "TMP_DIR"
    value: "/tmp"
  - key: "WIGWAG_NODE_PATH"
    value: "/usr/lib/pelion/devicejs-core-modules/node_modules"
  - key: "WIGWAG_DIR"
    value: "/usr/lib/pelion"
  - key: "NODE_EXEC"
    value: "/usr/lib/pelion/bin/node"
  - key: "MAESTRO_RUNNER_DIR"
    value: "/usr/lib/pelion/devicejs-core-modules/maestroRunner"
  - key: "RELAY_VERSIONS_FILE"
    value: "/etc/pelion/versions.json"
  - key: "FACTORY_VERSIONS_FILE"
    value: "/etc/pelion/factory/versions.json"
  - key: "USER_VERSIONS_FILE"
    value: "/etc/pelion/user/versions.json"
  - key: "UPGRADE_VERSIONS_FILE"
    value: "/etc/pelion/upgrade/versions.json"
gateway_capabilities:
  edge_core_socketpath: "/tmp/edge.sock"
  lwm2m_objectid: 33457
  gateway_resources:
  - name: "urn:fid:pelion.com:log:1.0.0"
    enable: true
    config_filepath: "/etc/pelion/pelion-base-config.yaml"
  - name: "urn:fid:pelion.com:terminal:1.0.0"
    enable: true
    config_filepath: "/etc/pelion/relay-term-config.json"
  - name: "urn:fid:pelion.com:kaas:1.0.0"
    enable: true
    config_filepath: "/etc/pelion/kubeconfig"
config_end: true
