ARG PREFIX
FROM ${PREFIX}pelion-bullseye-build

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
		apt-rdepends \
		git \
		lintian \
		python \
		quilt \
		ssh \
		vim

USER user
