ARG PREFIX
FROM ${PREFIX}pelion-bionic-build

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
		apt-rdepends \
		git \
		lintian \
		nodejs \
		python \
		quilt \
		ssh \
		vim \
		rsync \
		docker.io

USER user
