#!/bin/sh

PACKAGE=devicedb
URL=git@github.com:armPelionEdge/devicedb.git
REV=66859c16080c98dc4af5e75f3c093d0c9387e9b3
REL=1.9.4

PKG_AR="${PACKAGE}_$REL.orig.tar.gz"
PKG_DIR="${PACKAGE}-$REL"
PKG_DSC="${PACKAGE}_$REL.dsc"

# Download the code.
if [ ! -d repo ]; then
    git clone "$URL" repo
fi

# Create an archive for dpkg-source.
if [ ! -f "$PKG_AR" ]; then
    ( cd repo
      git checkout "$REV"
      git archive --prefix="$PKG_DIR/" -o "../$PKG_AR" HEAD )
fi

# Generate a source package and extract it.
if [ ! -d "$PKG_DIR" ]; then
    tar xf "$PKG_AR"
    cp -r debian.in "$PKG_DIR"/debian
    dpkg-source -b "$PKG_DIR"
fi

# Build a binary package.
( cd "$PKG_DIR"
  debuild -b -us -uc )
