#!/bin/bash

set -e

export PKG_CONFIG="${DEB_HOST_GNU_TYPE}"-pkg-config

#export CGO_ENABLED=1
export GOPATH="$(pwd)/go-workspace"

package=k3s.io/k3s
packagedir=$GOPATH/src/$package
origpath="$(pwd)"

rm -rf "$GOPATH"
set -- *
mkdir -p "$packagedir"
cp -r "$@" "$packagedir"/

cd "$packagedir"
sudo chmod 666 /var/run/docker.sock

echo "building for $OS_CPU"
SKIP_VALIDATE=true make

from_path="$packagedir/dist/artifacts/k3s"

echo "cp $from_path $origpath/"
cp "$from_path" "$origpath"/
